@startuml Поиск   
    autonumber

    actor Client
    
    participant UI

    Client -> UI: Нажимает кнопку "Расписание занятий"
    UI -> UI: Переходит на страничку "Справочник по преподавателям"
    Client <-- UI: Показывает страницу "Справочник по преподавателям"

    Client -> UI: Вводит данные в поисковую строку
    UI -> UI: Производит поиск из имеющихся данных
    Client <-- UI: Отображает найденные данные

@enduml



    