@startuml Сортировка   
    autonumber

    actor Client
    
    participant UI

    Client -> UI: Нажимает кнопку "Расписание занятий"
    UI -> UI: Переходит на страничку "Справочник по преподавателям"
    Client <-- UI: Показывает страницу "Справочник по преподавателям"

    Client -> UI: Нажимает на стрелочку рядом со столбцом, по которому происходит сортировка
    UI -> UI: Сортирует данные
    Client <-- UI: Отображает отсортированные данные

@enduml



    