@startuml Сохранение  
    autonumber

    actor Client
    
    participant UI
    participant Server
    participant Db

    Client -> UI: Нажимает кнопку "Расписание занятий"
    UI -> UI: Переходит на страничку "Справочник по преподавателям"
    Client <-- UI: Показывает страницу "Справочник по преподавателям"

    Client -> UI: Нажимает кнопку "Редактировать"
    UI -> UI: Отображает страницу с редактируемыми данными
    Client <-- UI: Показывает страницу с редактируемыми данными
    Client -> UI: Выбирает доступные часы
    UI -> UI: Отображает выбранные доступные часы
    Client <-- UI: Показывает выбранные доступные часы

    Client -> UI: Нажимает кнопку "Сохранить"
    UI -> Server: Отправка введенных данных
    Server -> Db: Запрос о сохранении данных 
    Server <-- Db: Отправка ответа 
    UI <-- Server: Отправка ответа
    Client <-- UI: Отображение ответа, что все успешно

@enduml



    