@startuml Компоненты
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component diagram for MeggatechInsider - API Application

Container(spa, "Single Page Application", "React JS", "Предоставляет все функции приложения через веб-браузер")
ContainerDb(db, "База данных", "MSSQL", "Хранит информацию о пользователе, данные для работы с расписанием и учителями")

Container_Boundary(api, "Core Application") {
    Component(sign, "Контроллер входа", "Веб-апи контроллер", "Позволяет пользователям войти в приложение")
    Component(sheduleSettings, "Настройки расписания", "Веб-апи контроллер", "Позволяет работать с настройками расписания")
    Component(teacherGuid, "Справочник по преподавателям для расписания", "Веб-апи контроллер", "Позволяет считывать и изменять информацию о преподавателях для расписания")
    Component(shedule, "Расписание", "Веб-апи контроллер", "Позволяет работать с расписанием")
    Component(subjects, "Учебный план. Предметы", "Веб-апи контроллер", "Позволяет пользователям добавлять пердметы и изменять их")
    Component(teachers, "Учебный план. Преподаватели", "Веб-апи контроллер", "Позволяет пользователям считывать и изменять информацию о преподавателях")
    Component(assignment, "Учебный план. Назначение", "Веб-апи контроллер", "Позволяет пользователям изменять назначение на уроки")
}

Container_Boundary(api, "Core Application") {
    Component(signServices, "Сервис с бизнес-логикой входа", "Сервис с бизнес-логикой", "В нем проходит основная работа над данными входа")
    Component(sheduleSettingsServices, "Сервис с бизнес-логикой настроек расписания", "Сервис с бизнес-логикой", "В нем проходит основная работа над данными настроек расписания")
    Component(teacherGuidServices, "Сервис с бизнес-логикой для справочника по преподавателям для расписания", "Сервис с бизнес-логикой", "В нем проходит основная работа над данными о преподавателях для расписания")
    Component(sheduleServices, "Сервис с бизнес-логикой расписания", "Сервис с бизнес-логикой", "В нем проходит основная работа над данными расписания")
    Component(subjectsServices, "Сервис с бизнес-логикой для Учебный план. Предметы", "Сервис с бизнес-логикой", "В нем проходит основная работа над данными предметов для расписания")
    Component(teachersServices, "Сервис с бизнес-логикой для Учебный план. Преподаватели", "Сервис с бизнес-логикой", "В нем проходит основная работа над данными о преподавателях")
    Component(assignmentServices, "Сервис с бизнес-логикой для Учебный план. Назначение", "Сервис с бизнес-логикой", "В нем проходит основная работа над данными назначения на уроки")
    Component(excel, "Шаблонизатор", "C#", "Преобразование данных в excel")
    Component(sheduleStorage, "Хранилище", "Сохраняет и загружает расписание")
    Component(databaseProvider, "Провайдер базы данных", "Работает с базой данных")
}

Rel(spa, sheduleSettings, 'HTTPS');
Rel(spa, teacherGuid, 'HTTPS');
Rel(spa, shedule, 'HTTPS');
Rel(spa, subjects, 'HTTPS');
Rel(spa, teachers, 'HTTPS');
Rel(spa, assignment, 'HTTPS');

Rel(sign, signServices, 'данные');
Rel(sheduleSettings, sheduleSettingsServices, 'данные');
Rel(teacherGuid, teacherGuidServices, 'данные');
Rel(shedule, sheduleServices, 'данные');
Rel(subjects, subjectsServices, 'данные');
Rel(teachers, teachersServices, 'данные');
Rel(assignment, assignmentServices, 'данные');

Rel(signServices, databaseProvider, 'чтение/запись');
Rel(sheduleSettingsServices, databaseProvider, 'чтение/запись');
Rel(teacherGuidServices, databaseProvider, 'чтение/запись');
Rel(sheduleServices, databaseProvider, 'чтение/запись');
Rel(subjectsServices, databaseProvider, 'чтение/запись');
Rel(teachersServices, databaseProvider, 'чтение/запись');
Rel(assignmentServices, databaseProvider, 'чтение/запись');

Rel(signServices, excel, 'данные');
Rel(sheduleSettingsServices, excel, 'данные');
Rel(teacherGuidServices, excel, 'данные');
Rel(sheduleServices, excel, 'данные');
Rel(subjectsServices, excel, 'данные');
Rel(teachersServices, excel, 'данные');
Rel(assignmentServices, excel, 'данные');

Rel(sheduleServices, sheduleStorage, 'данные');

Rel(databaseProvider, db, 'данные');

@enduml