@startuml Диаграмма контекста
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Диаграмма контекста

Person(director, "Директор", "Пользователь нашей системы")
Person(headTeacher, "Завуч", "Пользователь нашей системы")

System(system, "Внутренняя система работы с документацией", "Позволяет авторизоваться, составить отчеты по разным тематикам; работать с расписанием, преподавателями")

Rel(director, system, "Составление отчетов, работа с сотрудниками")
Rel(headTeacher, system, "Работа с расписанием")

@enduml