@startuml Activity
start
:Ввод пароля;
while (Ошибка при вводе пароля) is (да)
  :Повторить ввод пароля;
endwhile (нет)
  :Главное меню;
  fork
    :Выбор учебного года;
  fork again
    :Выбор раздела;
    fork
      :Вводные данные;
      fork
        :Основные настройки;
        fork
          :Справочник настройка учебного плана;
          :Редактировать;
          :Пользователь ввел данные;
          if(Сохранить изменения) then (да)
            :Изменения сохранены в бд;
          else (нет)
            :Редактирование закрылось, 
            отображаются данные 
            последнего сохранения;
          endif
        fork again
          :Справочник настройка зп;
          fork
            :Редактировать;
            if(Сохранить изменения) then (да)
              :Изменения сохранены в бд;
            else (нет)
              :Редактирование закрылось, 
              отображаются данные 
              последнего сохранения;
            endif
          fork again
            :Добавить;
            :Ввел данные;
            :Сохранить;
          fork again
            :Удалить;
            if(Подтвердить удаление) then (да)
              :Данные удалены из бд;
            else (нет)
              :Удаление отменилось,
              отображаются данные 
              последнего сохранения;
            endif
          endfork
        endfork
      fork again
        :Настройки преподавателей;
      fork again
        :Настройки предметов;
      fork again
        :Настройки расписания;
        fork
          :Справочник время проведения пар;
          fork
            :Добавить;
            :Ввел данные;
            :Сохранить;
          fork again
            :Удалить;
            if(Подтвердить удаление) then (да)
              :Данные удалены из бд;
            else (нет)
              :Удаление отменилось,
              отображаются данные 
              последнего сохранения;
            endif
          fork again
            :Выбрать сортировку;
            fork
                :Сортировка по времени начала;
                fork
                :От большего к меньшему;
                fork again
                :От меньшего к большему;
                endfork
            fork again
                :Сортировка по времени конца;
                fork
                :От большего к меньшему;
                fork again
                :От меньшего к большему;
                endfork
            endfork
          endfork
        fork again
          :Справочник время проведения уроков;
          fork
            :Добавить;
            :Ввел данные;
            :Сохранить;
          fork again
            :Выбрать сортировку;
            fork
              :Сортировка по времени начала;
              fork
                :От большего к меньшему;
              fork again
                :От меньшего к большему;
              endfork
            fork again
              :Сортировка по времени конца;
              fork
                :От большего к меньшему;
              fork again
                :От меньшего к большему;
              endfork
            endfork
          fork again
            :Удалить;
            if(Подтвердить удаление) then (да)
              :Данные удалены из бд;
            else (нет)
              :Удаление отменилось,
              отображаются данные 
              последнего сохранения;
            endif
          endfork
        fork again
          :Справочник проведение линейки;
          :Редактировать;
          :Пользователь ввел данные;
          :Выбрал день недели из списка;
          if(Сохранить изменения) then (да)
            :Изменения сохранены в бд;
          else (нет)
            :Редактирование закрылось, 
            отображаются данные 
            последнего сохранения;
          endif  
        endfork
      endfork
    fork again
      :Учебный план;
      fork
        :Предметы;
      fork again
        :Преподаватели;
      fork again
        :Учебный план;
      fork again
        :Назначение;    
      endfork
    fork again
      :Расписание;
      fork
        :Выбор учебной недели;
      fork again
        :Справочник по преподавателям;
        fork
          :Редактировать;
          :Выбрать из списка;
          if(Сохранить изменения) then (да)
            :Изменения сохранены в бд;
          else (нет)
            :Редактирование закрылось, 
            отображаются данные 
            последнего сохранения;
          endif
        fork again
          :Поиск;
          :Пользователь ввел данные;
          :Данные отфильтровались согласно поиску; 
        endfork
      fork again
        :Справочник по классам;
      fork again
        :Расписание; 
        fork
          :Панель;
          fork
          while(Нужны изменения) is (да)
            :Редактировать;
            :Выбрать день недели;
            :Выбрать пара/урок;
            :Выбрать время;
            :Выбрать классы;
            :Ввести кол-во подгрупп;
            :Выбрать подгруппу 
             для которой проставляется занятие;
            :Выбрать из списка предмет+преподаватель;
            if(Занятие онлайн) then (да)
            else (нет)
              :Выбрать кабинет;
            endif
            :Выбрать деление по 
            группам/паралелли/классам 
            для отчетов;
            if() then (Сохранить)
              :Изменения перенеслись 
              в рабочую область;
            else (Очистить)
              :Панель в дефолтном виде;
            endif 
          endwhile (нет) 
          fork again
          if (Учебный план на текущуюю и на рассматриваемую неделю совпадают) then (да)
            :Применить для текущей недели;  
            :В бд на текущую неделю записывается 
             такое же расписание, 
             как на рассматриваемой;
          else (нет)
          endif
          fork again
            :Сохранить в табель;
            :Расписание недели учитывается 
            в месячном табеле;
          fork again
            :Сохранить в excel; 
            :Скачивается файл excel с расписанием;
          endfork
        fork again
          :Рабочая область;
          fork
            :Редактировать ячейку;
            :Данные подтягиваются в форму редактирования;
          fork again
            :Удалить ячейку; 
            :Очищается выбранная ячейка;
          endfork
        endfork  
      endfork
    endfork
  endfork
stop
@enduml