@startuml Диаграмма состояний

[*] --> Вход
    Вход : entry / Ввод пароля
    Вход : do / Выбор учебного года
    Вход : exit / Выбор пункта меню

Вход --> Вводные_данные
    Вводные_данные : entry / Отображение страницы "основные настройки"
    Вводные_данные : do / Переход на основные настройки
    Вводные_данные : do / Переход на настройки преподавателей
    Вводные_данные : do / Переход на настройки предметов
    Вводные_данные : do / Переход на настройки расписания

Вводные_данные --> Основные_настройки
Основные_настройки --> Настройка_учебного_плана
    Настройка_учебного_плана : do / Ввод количества классов
    Настройка_учебного_плана : do / Ввод количества недель в каждой четверти
    Настройка_учебного_плана : do / Ввод начала каждой четверти
    Настройка_учебного_плана : do / Редактирование данных
    Настройка_учебного_плана : do / Сохранение изменений после редактирования
    Настройка_учебного_плана : do / Отмена изменений

Основные_настройки --> Настройка_зарплат
    Настройка_зарплат : do / Добавить новый коэффициент
    Настройка_зарплат : do / Удалить коэффициент
    Настройка_зарплат : do / Редактирование коэффициента
    Настройка_зарплат : do / Найти коэффициенты настройки с помощью поиска
    Настройка_зарплат : do / Сохранение изменений после редактирования
    Настройка_зарплат : do / Отмена изменений

Вводные_данные --> Настройки_преподавателей
Настройки_преподавателей --> Типы_договоров
    Типы_договоров : do / Добавить тип договора
    Типы_договоров : do / Удалить тип договора
    Типы_договоров : do / Упорядочить типы договоров по алфавиту
    Типы_договоров : do / Поиск по названию типа договоров

Настройки_преподавателей --> Категории_преподавателей
    Категории_преподавателей : do / Добавить категорию предметов
    Категории_преподавателей : do / Удалить категорию предметов
    Категории_преподавателей : do / Найти категорию с помощью поиска
    Категории_преподавателей : do / Сортировка категорий по алфавиту

Настройки_преподавателей --> Образование_преподавателей
    Образование_преподавателей : do / Ввести тип образования
    Образование_преподавателей : do / Сохранить тип образования
    Образование_преподавателей : do / Удалить тип образования
    Образование_преподавателей : do / Упорядочить типы образования по алфавиту
    Образование_преподавателей : do / Выбрать порядок упорядочивания по названию элемента
    Образование_преподавателей : do / Редактировать информацию по коэффициентам
    Образование_преподавателей : do / Поиск по образованию преподавателей
    Образование_преподавателей : do / Отсортировать коэффициенты

Вводные_данные --> Настройки_предметов
Настройки_предметов --> Финансирование_предмета
    Финансирование_предмета : do / Добавить тип финансирования
    Финансирование_предмета : do / Удалить тип финансирования
    Финансирование_предмета : do / Упорядочить финансирование по алфавиту

Настройки_предметов --> Справочник_предметов
Справочник_предметов --> Категории_предметов
    Категории_предметов : do / Добавить категорию предметов
    Категории_предметов : do / Удалить категорию предметов
    Категории_предметов : do / Найти категорию с помощью поиска
    Категории_предметов : do / Сортировка категорий по алфавиту

Справочник_предметов --> Является_основным
    Является_основным : do / Сохранить новый элемент справочника
    Является_основным : do / Добавить новый элемент справочника
    Является_основным : do / Удалить элемент справочника
    Является_основным : do / Упорядочить элементы по алфавиту
    Является_основным : do / Поиск по основным/неосновным предметам

Справочник_предметов --> Является_углубленным
    Является_углубленным : do / Добавить категорию
    Является_углубленным : do / Удалить категорию
    Является_углубленным : do / Ввести коэффициент
    Является_углубленным : do / Упорядочить по категориям
    Является_углубленным : do / Упорядочить по коэффициенту
    Является_углубленным : do / Поиск по углубленным и неуглубленным предметам

Настройки_предметов --> Типы_предметов
    Типы_предметов : do / Добавить новый тип предметов
    Типы_предметов : do / Удалить тип предметов
    Типы_предметов : do / Редактирование параметров типа предметов
    Типы_предметов : do / Найти тип предметов с помощью поиска
    Типы_предметов : do / Сохранение изменений после редактирования
    Типы_предметов : do / Отмена изменений
    Типы_предметов : do / Сортировка типов предметов по алфавиту

Вводные_данные --> Настройки_расписания
Настройки_расписания --> Время_проведения_пар
    Время_проведения_пар : do / Добавить время пары
    Время_проведения_пар : do / Удалить время пары
    Время_проведения_пар : do / Отсортировать по времени начала/окончания пары

Настройки_расписания --> Время_проведения_уроков
    Время_проведения_уроков : do / Добавить время урока
    Время_проведения_уроков : do / Удалить время урока
    Время_проведения_уроков : do / Отсортировать по времени начала/окончания урока

Настройки_расписания --> Проведение_линейки
    Проведение_линейки : do / Установить день недели
    Проведение_линейки : do / Установить время начала и окончания линейки
    Проведение_линейки : do / Сохранить изменения
    Проведение_линейки : do / Отменить несохраненные изменения

Вход --> Учебный_план
Учебный_план --> Предметы
    Предметы : do / Получить данные по предметам
    Предметы : do / Добавить предмет
    Предметы : do / Редактировать предмет
    Предметы : do / Удалить предмет
    Предметы : do / Найти предмет
    Предметы : do / Отсортировать предметы по столбцам
    Предметы : do / Сохранить изменения
    Предметы : do / Отменить изменения
    Предметы : do / Редактировать информацию принадлежности предмета к ЕГЭ

Учебный_план --> Преподаватели
    Преподаватели : do / Получить данные по преподавателям
    Преподаватели : do / Добавить преподавателя и данные по нему
    Преподаватели : do / Редактировать преподавателя
    Преподаватели : do / Удалить преподавателя
    Преподаватели : do / Найти преподавателя
    Преподаватели : do / Отсортировать преподавателей по столбцам(алфавит, дата, цифры)
    Преподаватели : do / Сохранить изменения
    Преподаватели : do / Отменить изменения
    Преподаватели : do / редактировать информацию учета в параметрах зарплаты преподавателя

Учебный_план --> учебный_план
    учебный_план : do / Очистить четверть
    учебный_план : do / Сортировка по возрастанию и убыванию
    учебный_план : do / Выбирать столбец по которому сортировать информацию
    учебный_план : do / Автозаполнение четвертей по первым 2 неделям
    учебный_план : do / Редактирование четвертей
    учебный_план : do / Переключаться между 10 и 11 классом

Учебный_план --> Назначение
    Назначение : do / Получить данные по назначениям
    Назначение : do / Добавить назначение
    Назначение : do / Редактировать назначение
    Назначение : do / Удалить назначение
    Назначение : do / Найти назначение
    Назначение : do / Отсортировать назначения по столбцам
    Назначение : do / Получить расхождения по назначениям
    Назначение : do / Выбрать класс для назначений
    Назначение : do / Сохранить изменения
    Назначение : do / Отменить изменения

Вход --> Финансовый_отчет
Финансовый_отчет --> Тарификация
    Тарификация : do / Выгрузить в формат excel
    Тарификация : do / Выбирать столбец по которому сортировать информацию
    Тарификация : do / Поиск по ключевому слову в таблице

Финансовый_отчет --> Внебюджет
    Внебюджет : do / Выгрузить в формат excel
    Внебюджет : do / Выбирать столбец по которому сортировать информацию
    Внебюджет : do / Поиск по ключевому слову в таблице

Финансовый_отчет --> Финальный_отчет
    Финальный_отчет : do / Выгрузить в формат excel
    Финальный_отчет : do / Выбирать столбец по которому сортировать информацию
    Финальный_отчет : do / Поиск по ключевому слову в таблице

Финансовый_отчет --> Внебюджетные_категории
    Внебюджетные_категории : do / Получить данные по внебюджетным категориям
    Внебюджетные_категории : do / Добавить внебюджетную категорию и стоимость часа
    Внебюджетные_категории : do / Редактировать внебюджетную категорию
    Внебюджетные_категории : do / Найти внебюджетную категорию
    Внебюджетные_категории : do / Сохранять пропорцию при выводе внебюджетных категорий
    Внебюджетные_категории : do / Отсортировать внебюджетные категории по столбцам
    Внебюджетные_категории : do / Сохранить изменения
    Внебюджетные_категории : do / Отменить изменения

Вход --> Статистика
Статистика --> Статистика_бюджетов
Статистика_бюджетов --> Статистика_бюджетов_10_класс
    Статистика_бюджетов_10_класс : do / Выбирать столбец по которому сортировать информацию
    Статистика_бюджетов_10_класс : do / Поиск по ключевому слову в таблице

Статистика_бюджетов --> Статистика_бюджетов_11_класс
    Статистика_бюджетов_11_класс : do / Выбирать столбец по которому сортировать информацию
    Статистика_бюджетов_11_класс : do / Поиск по ключевому слову в таблице

Статистика_бюджетов --> Статистика_бюджетов_общая
    Статистика_бюджетов_общая : do / Выбирать столбец по которому сортировать информацию
    Статистика_бюджетов_общая : do / Поиск по ключевому слову в таблице

Статистика --> Статистика_категорий
    Статистика_категорий : do / Выбирать столбец по которому сортировать информацию
    Статистика_категорий : do / Поиск по ключевому слову в таблице

Статистика --> Статистика_преподавателей
    Статистика_преподавателей : do / Выбирать столбец по которому сортировать информацию
    Статистика_преподавателей : do / Поиск по ключевому слову в таблице

Вход --> План_курсов

Вход --> Расписание_занятий

Вход --> Расписание_курсов

Вход --> Контроль_учебного_плана_за_месяц
    Контроль_учебного_плана_за_месяц : do / Выгрузить в формат excel
    Контроль_учебного_плана_за_месяц : do / Выбирать столбец по которому сортировать информацию
    Контроль_учебного_плана_за_месяц : do / Поиск по ключевому слову в таблице
    Контроль_учебного_плана_за_месяц : do / Переключение между месяцами
    Контроль_учебного_плана_за_месяц : do / Переключение между договорами
    Контроль_учебного_плана_за_месяц : do / Открыть просмотр комментариев

Вход --> Контроль_учебного_плана_за_год
    Контроль_учебного_плана_за_год : do / Выгрузить в формат excel
    Контроль_учебного_плана_за_год : do / Выбирать столбец по которому сортировать информацию
    Контроль_учебного_плана_за_год : do / Поиск по ключевому слову в таблице
    Контроль_учебного_плана_за_год : do / Переключение между месяцами
    Контроль_учебного_плана_за_год : do / Переключение между договорами
    Контроль_учебного_плана_за_год : do / Открыть просмотр комментариев

@enduml