@startuml UseCase

left to right direction
Пользователь --> (Ввод данных в справочники)
Пользователь --> (Ввод данных о преподавателях/предматах)
Пользователь --> (Редактирование учебного плана)
Пользователь --> (Редактирование данных финансового отчета)
Пользователь --> (Получение финансового отчета)
Пользователь --> (Получение отчетов)
Пользователь --> (Составление расписания занятий)
Пользователь --> (Ввод данных по отработанным часам/причинам неотработанных часов)
Пользователь --> (Получение отчета по контролю загрузки)
Пользователь --> (Распределение учебных часов по преподавателям)

(Ввод данных в справочники) ..> (Составление учебного плана) : include
(Ввод данных о преподавателях/предматах) ..> (Составление учебного плана) : include
(Редактирование учебного плана) ..> (Составление учебного плана) : extend

(Редактирование данных финансового отчета) .> (Получение финансового отчета) : extend

(Ввод данных по отработанным часам/причинам неотработанных часов) .> (Получение отчета по контролю загрузки) : include

(Составление учебного плана) ..> (Распределение учебных часов по преподавателям) : include
(Распределение учебных часов по преподавателям) .> (Сбор статистика) : include
(Сбор статистика) .> (Получение отчетов) : include
(Распределение учебных часов по преподавателям) .left.> (Составление расписания занятий) : include
(Редактирование расписания) .> (Составление расписания занятий) : extend
(Распределение учебных часов по преподавателям) .left.> (Ввод данных по отработанным часам/причинам неотработанных часов) : include

(Всегда) -> (Контроль соответствия введенным параметрам)
@enduml