@startuml Диаграмма компонентов

' Скины и стили
skinparam componentStyle rectangle
skinparam wrapWidth 250
skinparam packageStyle rectangle
skinparam monochrome true
skinparam defaultFontName Arial

package "MeggatechInsider" {

  component WebApplication as "Клиентское приложение"

  component Server as "Сервер приложения"

  component Database as "База данных"

  WebApplication --> Server : "Отправка запроса"
  Server --> Database : "Запрашиваем данные"
  Database --> Server : "Передача данных"
  Server --> WebApplication : "Передача данных"
}

@enduml