@startuml Выбор недели
    autonumber

    actor Client
    
    participant UI

    Client -> UI: Нажимает кнопку "Расписание занятий"
    UI -> UI: Переходит на страничку "Расписание занятий"
    Client <-- UI: Показывает страницу "Расписание занятий"
    Client -> UI: Выбирает неделю
    Client <-- UI: Отображает выбранную неделю
@enduml