@startuml Применение к неделе
    autonumber

    actor Client
    
    participant UI
    participant Server
    participant Db

    Client -> UI: Нажимает кнопку "Расписание занятий"
    UI -> UI: Переходит на страничку "Расписание занятий"
    Client <-- UI: Показывает страницу "Расписание занятий"
    Client -> UI: Заполняет данные: день недели, время, урок или пара, классы, количество подгрупп, предмет, кабинет, деление по составам.
    UI -> UI: Преобразует в нужный формат и хранит в кэше
    Client <-- UI: Отображает введенные данные
    Client -> UI: Нажимает кнопку "Применить для текущей недели"
    UI -> Server: Отправка данных
    Server -> Db: Запрос об добавлении данных 
    Server <-- Db: Отправка ответа 
    UI <-- Server: Отправка ответа
    Client <-- UI: Отображение ответа, что все успешно
@enduml