@startuml Отмена добавления времени проведения линейки    
    autonumber

    actor Client
    
    participant UI
    participant Server
    participant Db

    Client -> UI: Нажимает кнопку "Настройки расписания"
    UI -> UI: Переходит на страничку "Настройки расписания"
    Client <-- UI: Показывает страницу "Настройки расписания"

    Client -> UI: Выбирает справочник "Проведение линейки", выбирает день недели
    UI -> UI: Отображает выбранный день недели
    Client <-- UI: Показывает выбранный день недели
    Client -> UI: Вводит время проведения линейки
    UI -> UI: Отображает введенное время
    Client <-- UI: Показывает введенно время
    Client -> UI: Вводит Комментарий
    UI -> UI: Отображает введенный комментарий
    Client <-- UI: Показывает введенный комментарий

    Client -> UI: Нажимает кнопку "Отменить"
    UI -> UI: Очистил введенные данные
    Client <-- UI: Отображение пустых полей

@enduml
