@startuml
start
fork
    :Добавить;
    repeat :Пользователь ввел данные;
        :Валидация данных;
        -> Проверка данных;
        if (Данные валидны) then (Да)
            if(Сохранить изменения) then (да)
                :Изменения сохранены в бд;
                stop
            else (нет)
                :Отображаются данные 
                последнего сохранения;
                stop
            endif
        else (Нет)
            :Вывод ошибки;
        endif
    repeatwhile
fork again
    :Удалить;
    if(Подтвердить удаление) then (да)
        :Данные удалены из бд;
    else (нет)
        :Удаление отменилось,
        отображаются данные 
        последнего сохранения;
    endif
fork again
    fork
    :Справочники "Основные настройки", "Настройки предметов", "Финансирование предметов", "Типы предметов", "Настройка преподавателей", "Настройки расписания", "Предметы";
    fork
    :Редактировать;
                if(Сохранить изменения) then (да)
                  :Изменения сохранены в бд;
                else (нет)
                  :Редактирование закрылось, 
                  отображаются данные 
                  последнего сохранения;
                endif
    fork again
    :Справочники "Настройки предметов", "Финансирование предметов", "Типы предметов", "Настройка преподавателей", "Настройки расписания", "Предметы";
    :Cортировать;
    if(Выбрать сортировку) then (От большего к меньшему)
      :Отображение сортированных данных;
    else (От меньшего к большему)
      : Отображение сортированных данных;
    endif
@enduml