@startuml

package Development {
    component "Разработчик" as developer
    component "Гитхаб-репозиторий" as github
    rectangle "Добавление в область добавленных файлов" as add
    rectangle "Коммит" as commit

    developer --> add : "git add"
    add --> commit: "git commit"
    commit --> github: "git push"
}

package Production {
    node "Докер" as docker {
        component "Веб-приложение"
        component ".NET-приложение"
        database "База данных"
    }
}

package GithubActions {
    rectangle "checkout" as checkout
    rectangle "login" as login
    rectangle "Extract metadata" as metadata
    rectangle "build and push frontend" as frontend
    rectangle "build and push backend" as backend
    rectangle "Images in DockerHub" as DockerHub
}

File Script {
    rectangle "docker-compose down" as down
    rectangle "docker-compose up --build -d" as up
}

github --> GithubActions : "run pipeline"

checkout --> login
login --> metadata
metadata --> frontend
frontend --> backend
backend --> DockerHub

DockerHub --> Script

down --> up
up --> docker

@enduml