@startuml Сортировка    
    autonumber

    actor Client
    
    participant UI
    participant Server
    participant Db

    Client -> UI: Нажимает кнопку "Вводные данные"
    UI -> UI: Переходит на страничку "Основные настройки"
    Client <-- UI: Показывает страницу "Основные настройки"

    Client -> UI: Нажимает кнопку "Настройки расписания"
    UI -> UI: Переходит на страничку "Настройки расписания"
    Client <-- UI: Показывает страницу "Настройки расписания"
    Client -> UI: Выбирает справочник "Время проведения уроков"
    UI -> UI: Отображает поля ввода для времени начала урока и времени конца урока
    Client <-- UI: Показывает данные пользователю

    Client -> UI: Нажимает на стрелочку рядом со столбцом, по которому происходит сортировка
    UI -> UI: Сортирует данные
    Client <-- UI: Отображает отсортированные данные

@enduml
