@startuml Удаление времени проведения уроков    
    autonumber

    actor Client
    
    participant UI
    participant Server
    participant Db

    Client -> UI: Нажимает кнопку "Вводные данные"
    UI -> UI: Переходит на страничку "Основные настройки"
    Client <-- UI: Показывает страницу "Основные настройки"

    Client -> UI: Нажимает кнопку "Настройки расписания"
    UI -> UI: Переходит на страничку "Настройки расписания"
    Client <-- UI: Показывает страницу "Настройки расписания"

    Client -> UI: Выбирает справочник "Время проведения уроков",нажимает кнопку "удалить" у любой из пар
    UI -> Server: Отправка введенных данных
    Server -> Db: Запрос об удалении данных 
    Server <-- Db: Отправка ответа 
    UI <-- Server: Отправка ответа
    Client <-- UI: Отображение ответа, что все успешно

@enduml
