@startuml Отмена добавления времени проведения пар    
    autonumber

    actor Client
    
    participant UI
    participant Server
    participant Db

    Client -> UI: Нажимает кнопку "Вводные данные"
    UI -> UI: Переходит на страничку "Основные настройки"
    Client <-- UI: Показывает страницу "Основные настройки"

    Client -> UI: Нажимает кнопку "Настройки расписания"
    UI -> UI: Переходит на страничку "Настройки расписания"
    Client <-- UI: Показывает страницу "Настройки расписания"
    Client -> UI: Выбирает справочник "Время проведения пар",нажимает кнопку "добавить"
    UI -> UI: Отображает поля ввода для времени начала пары и времени конца пары
    Client -> UI: Вводит время начала и конца пары
    UI -> UI: Отображает введенное время

    Client -> UI: Нажимает кнопку "Отменить"
    UI -> UI: Очистил введенные данные
    Client <-- UI: Отображение пустых полей

@enduml
