@startuml Сортировка  
    autonumber

    actor Client
    
    participant UI
    participant Client

    Client -> UI: Нажимает кнопку "Предметы"
    UI -> UI: Переходит на страничку "Предметы"
    Client <-- UI: Показывает страницу "Предметы"

    Client -> UI: Выбирает справочник "Предметы"

    Client <-- UI: Показывает данные
    
    Client -> UI: Нажимает на стрелочку рядом со столбцом, по которому происходит сортировка
    UI -> UI: Сортирует данные
    Client <-- UI: Отображает отсортированные данные
    
@enduml
