@startuml Поиск  
    autonumber

    actor Client
    
    participant UI

    Client -> UI: Нажимает кнопку "Учебный план"
    UI -> UI: Переходит на страничку "Предметы"
    Client <-- UI: Показывает страницу "Предметы"

    Client -> UI: Нажимает кнопку "Преподаватели"
    UI -> UI: Переходит на страничку "Преподаватели"
    Client <-- UI: Показывает страницу "Преподаватели"

    Client -> UI: Вводит данные в поисковую строку
    UI -> UI: Производит поиск из имеющихся данных
    Client <-- UI: Отображает найденные данные

@enduml