@startuml Редактирование преподавателя
    autonumber

    actor Client
    
    participant UI
    participant Server
    participant Db

    Client -> UI: Нажимает кнопку "Преподаватели"
    UI -> UI: Переходит на страничку "Преподаватели"
    Client <-- UI: Показывает страницу "Преподаватели"

    Client -> UI: Нажимает на кнопку "Редактировать"
    UI -> UI: Отображает поля для редактирования
    Client <-- UI: Показывает поля для редактирования
    Client -> UI: Изменяет данные: ФИО, категория, договор, образование, дата начала работы, стаж на момент устройства, дата рождения
    UI -> UI: Запоминает данные
    Client <-- UI: Показывает введенные данные
    Client -> UI: Нажимает на галочку(кнопку сохранения)
    UI -> Server: Форматирует данные, отправляет запрос на обновление
    Server -> Db: Запрос об обвновлении данных
    Server <-- Db: Отправка ответа
    UI <-- Server: Отправка ответа
    Client <-- UI: Отображение ответа, что все успешно

@enduml