@startuml Сортировка    
    autonumber

    actor Client
    
    participant UI

    Client -> UI: Нажимает кнопку "Преподаватели"
    UI -> UI: Переходит на страничку "Преподаватели"
    Client <-- UI: Показывает страницу "Преподаватели"

    Client -> UI: Нажимает на стрелочку рядом со столбцом, по которому происходит сортировка
    UI -> UI: Сортирует данные
    Client <-- UI: Отображает отсортированные данные

@enduml